package com.briup.jz.dao;

import com.briup.jz.bean.BaseLog;
import com.briup.jz.bean.BaseLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BaseLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_log
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    long countByExample(BaseLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_log
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    int deleteByExample(BaseLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_log
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_log
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    int insert(BaseLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_log
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    int insertSelective(BaseLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_log
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    List<BaseLog> selectByExample(BaseLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_log
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    BaseLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_log
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    int updateByExampleSelective(@Param("record") BaseLog record, @Param("example") BaseLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_log
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    int updateByExample(@Param("record") BaseLog record, @Param("example") BaseLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_log
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    int updateByPrimaryKeySelective(BaseLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_log
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    int updateByPrimaryKey(BaseLog record);
}