package com.briup.jz.dao;

import com.briup.jz.bean.BaseFile;
import com.briup.jz.bean.BaseFileExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BaseFileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_file
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    long countByExample(BaseFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_file
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    int deleteByExample(BaseFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_file
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_file
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    int insert(BaseFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_file
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    int insertSelective(BaseFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_file
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    List<BaseFile> selectByExample(BaseFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_file
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    BaseFile selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_file
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    int updateByExampleSelective(@Param("record") BaseFile record, @Param("example") BaseFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_file
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    int updateByExample(@Param("record") BaseFile record, @Param("example") BaseFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_file
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    int updateByPrimaryKeySelective(BaseFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_file
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    int updateByPrimaryKey(BaseFile record);
}