package com.briup.jz.dao;

import com.briup.jz.bean.BaseRolePrivilege;
import com.briup.jz.bean.BaseRolePrivilegeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BaseRolePrivilegeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_role_privilege
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    long countByExample(BaseRolePrivilegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_role_privilege
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    int deleteByExample(BaseRolePrivilegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_role_privilege
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_role_privilege
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    int insert(BaseRolePrivilege record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_role_privilege
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    int insertSelective(BaseRolePrivilege record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_role_privilege
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    List<BaseRolePrivilege> selectByExample(BaseRolePrivilegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_role_privilege
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    BaseRolePrivilege selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_role_privilege
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    int updateByExampleSelective(@Param("record") BaseRolePrivilege record, @Param("example") BaseRolePrivilegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_role_privilege
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    int updateByExample(@Param("record") BaseRolePrivilege record, @Param("example") BaseRolePrivilegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_role_privilege
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    int updateByPrimaryKeySelective(BaseRolePrivilege record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_role_privilege
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    int updateByPrimaryKey(BaseRolePrivilege record);
}