package com.briup.jz.dao;

import com.briup.jz.bean.BaseConfig;
import com.briup.jz.bean.BaseConfigExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BaseConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_config
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    long countByExample(BaseConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_config
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    int deleteByExample(BaseConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_config
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_config
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    int insert(BaseConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_config
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    int insertSelective(BaseConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_config
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    List<BaseConfig> selectByExample(BaseConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_config
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    BaseConfig selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_config
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    int updateByExampleSelective(@Param("record") BaseConfig record, @Param("example") BaseConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_config
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    int updateByExample(@Param("record") BaseConfig record, @Param("example") BaseConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_config
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    int updateByPrimaryKeySelective(BaseConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_config
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    int updateByPrimaryKey(BaseConfig record);
}