package com.briup.jz.dao;

import com.briup.jz.bean.Carousel;
import com.briup.jz.bean.CarouselExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CarouselMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_carousel
     *
<<<<<<< HEAD
     * @mbg.generated Thu Jun 03 18:31:33 CST 2021
=======
     * @mbg.generated Thu Jun 03 16:08:43 CST 2021
>>>>>>> 0e922cda61c85a780bd8f647d108582e3274f252
     */
    long countByExample(CarouselExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_carousel
     *
<<<<<<< HEAD
     * @mbg.generated Thu Jun 03 18:31:33 CST 2021
=======
     * @mbg.generated Thu Jun 03 16:08:43 CST 2021
>>>>>>> 0e922cda61c85a780bd8f647d108582e3274f252
     */
    int deleteByExample(CarouselExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_carousel
     *
<<<<<<< HEAD
     * @mbg.generated Thu Jun 03 18:31:33 CST 2021
=======
     * @mbg.generated Thu Jun 03 16:08:43 CST 2021
>>>>>>> 0e922cda61c85a780bd8f647d108582e3274f252
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_carousel
     *
<<<<<<< HEAD
     * @mbg.generated Thu Jun 03 18:31:33 CST 2021
=======
     * @mbg.generated Thu Jun 03 16:08:43 CST 2021
>>>>>>> 0e922cda61c85a780bd8f647d108582e3274f252
     */
    int insert(Carousel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_carousel
     *
<<<<<<< HEAD
     * @mbg.generated Thu Jun 03 18:31:33 CST 2021
=======
     * @mbg.generated Thu Jun 03 16:08:43 CST 2021
>>>>>>> 0e922cda61c85a780bd8f647d108582e3274f252
     */
    int insertSelective(Carousel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_carousel
     *
<<<<<<< HEAD
     * @mbg.generated Thu Jun 03 18:31:33 CST 2021
=======
     * @mbg.generated Thu Jun 03 16:08:43 CST 2021
>>>>>>> 0e922cda61c85a780bd8f647d108582e3274f252
     */
    List<Carousel> selectByExample(CarouselExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_carousel
     *
<<<<<<< HEAD
     * @mbg.generated Thu Jun 03 18:31:33 CST 2021
=======
     * @mbg.generated Thu Jun 03 16:08:43 CST 2021
>>>>>>> 0e922cda61c85a780bd8f647d108582e3274f252
     */
    Carousel selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_carousel
     *
<<<<<<< HEAD
     * @mbg.generated Thu Jun 03 18:31:33 CST 2021
=======
     * @mbg.generated Thu Jun 03 16:08:43 CST 2021
>>>>>>> 0e922cda61c85a780bd8f647d108582e3274f252
     */
    int updateByExampleSelective(@Param("record") Carousel record, @Param("example") CarouselExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_carousel
     *
<<<<<<< HEAD
     * @mbg.generated Thu Jun 03 18:31:33 CST 2021
=======
     * @mbg.generated Thu Jun 03 16:08:43 CST 2021
>>>>>>> 0e922cda61c85a780bd8f647d108582e3274f252
     */
    int updateByExample(@Param("record") Carousel record, @Param("example") CarouselExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_carousel
     *
<<<<<<< HEAD
     * @mbg.generated Thu Jun 03 18:31:33 CST 2021
=======
     * @mbg.generated Thu Jun 03 16:08:43 CST 2021
>>>>>>> 0e922cda61c85a780bd8f647d108582e3274f252
     */
    int updateByPrimaryKeySelective(Carousel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_carousel
     *
<<<<<<< HEAD
     * @mbg.generated Thu Jun 03 18:31:33 CST 2021
=======
     * @mbg.generated Thu Jun 03 16:08:43 CST 2021
>>>>>>> 0e922cda61c85a780bd8f647d108582e3274f252
     */
    int updateByPrimaryKey(Carousel record);
}