package com.briup.jz.dao;

import com.briup.jz.bean.OrderComment;
import com.briup.jz.bean.OrderCommentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jz_order_comment
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    long countByExample(OrderCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jz_order_comment
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    int deleteByExample(OrderCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jz_order_comment
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jz_order_comment
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    int insert(OrderComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jz_order_comment
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    int insertSelective(OrderComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jz_order_comment
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    List<OrderComment> selectByExample(OrderCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jz_order_comment
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    OrderComment selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jz_order_comment
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    int updateByExampleSelective(@Param("record") OrderComment record, @Param("example") OrderCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jz_order_comment
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    int updateByExample(@Param("record") OrderComment record, @Param("example") OrderCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jz_order_comment
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    int updateByPrimaryKeySelective(OrderComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jz_order_comment
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    int updateByPrimaryKey(OrderComment record);
}