package com.briup.jz.dao;

import com.briup.jz.bean.Platform;
import com.briup.jz.bean.PlatformExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PlatformMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jz_platform
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    long countByExample(PlatformExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jz_platform
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    int deleteByExample(PlatformExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jz_platform
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jz_platform
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    int insert(Platform record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jz_platform
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    int insertSelective(Platform record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jz_platform
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    List<Platform> selectByExample(PlatformExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jz_platform
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    Platform selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jz_platform
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    int updateByExampleSelective(@Param("record") Platform record, @Param("example") PlatformExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jz_platform
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    int updateByExample(@Param("record") Platform record, @Param("example") PlatformExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jz_platform
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    int updateByPrimaryKeySelective(Platform record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jz_platform
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    int updateByPrimaryKey(Platform record);
}