package com.briup.jz.dao;

import com.briup.jz.bean.ProductCategory;
import com.briup.jz.bean.ProductCategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProductCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jz_product_category
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    long countByExample(ProductCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jz_product_category
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    int deleteByExample(ProductCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jz_product_category
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jz_product_category
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    int insert(ProductCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jz_product_category
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    int insertSelective(ProductCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jz_product_category
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    List<ProductCategory> selectByExample(ProductCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jz_product_category
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    ProductCategory selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jz_product_category
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    int updateByExampleSelective(@Param("record") ProductCategory record, @Param("example") ProductCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jz_product_category
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    int updateByExample(@Param("record") ProductCategory record, @Param("example") ProductCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jz_product_category
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    int updateByPrimaryKeySelective(ProductCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jz_product_category
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    int updateByPrimaryKey(ProductCategory record);
}