package com.briup.jz.bean;

import java.io.Serializable;

public class Article implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_article.id
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_article.title
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_article.content
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_article.publish_time
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    private Long publishTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_article.read_times
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    private Long readTimes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_article.status
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_article.thump_up
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    private Long thumpUp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_article.cover
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    private String cover;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_article.project_id
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    private Long projectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_article.author_id
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    private Long authorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_article.category_id
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    private Long categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_article.compony_id
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    private Long componyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cms_article
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_article.id
     *
     * @return the value of cms_article.id
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_article.id
     *
     * @param id the value for cms_article.id
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_article.title
     *
     * @return the value of cms_article.title
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_article.title
     *
     * @param title the value for cms_article.title
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_article.content
     *
     * @return the value of cms_article.content
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_article.content
     *
     * @param content the value for cms_article.content
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_article.publish_time
     *
     * @return the value of cms_article.publish_time
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    public Long getPublishTime() {
        return publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_article.publish_time
     *
     * @param publishTime the value for cms_article.publish_time
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    public void setPublishTime(Long publishTime) {
        this.publishTime = publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_article.read_times
     *
     * @return the value of cms_article.read_times
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    public Long getReadTimes() {
        return readTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_article.read_times
     *
     * @param readTimes the value for cms_article.read_times
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    public void setReadTimes(Long readTimes) {
        this.readTimes = readTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_article.status
     *
     * @return the value of cms_article.status
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_article.status
     *
     * @param status the value for cms_article.status
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_article.thump_up
     *
     * @return the value of cms_article.thump_up
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    public Long getThumpUp() {
        return thumpUp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_article.thump_up
     *
     * @param thumpUp the value for cms_article.thump_up
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    public void setThumpUp(Long thumpUp) {
        this.thumpUp = thumpUp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_article.cover
     *
     * @return the value of cms_article.cover
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    public String getCover() {
        return cover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_article.cover
     *
     * @param cover the value for cms_article.cover
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    public void setCover(String cover) {
        this.cover = cover == null ? null : cover.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_article.project_id
     *
     * @return the value of cms_article.project_id
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    public Long getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_article.project_id
     *
     * @param projectId the value for cms_article.project_id
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    public void setProjectId(Long projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_article.author_id
     *
     * @return the value of cms_article.author_id
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    public Long getAuthorId() {
        return authorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_article.author_id
     *
     * @param authorId the value for cms_article.author_id
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    public void setAuthorId(Long authorId) {
        this.authorId = authorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_article.category_id
     *
     * @return the value of cms_article.category_id
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    public Long getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_article.category_id
     *
     * @param categoryId the value for cms_article.category_id
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    public void setCategoryId(Long categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_article.compony_id
     *
     * @return the value of cms_article.compony_id
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    public Long getComponyId() {
        return componyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_article.compony_id
     *
     * @param componyId the value for cms_article.compony_id
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    public void setComponyId(Long componyId) {
        this.componyId = componyId;
    }
}