package com.briup.jz.bean;

import java.io.Serializable;

public class BaseRolePrivilege implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_role_privilege.id
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_role_privilege.role_id
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    private Long roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_role_privilege.privilege_id
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    private Long privilegeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table base_role_privilege
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_role_privilege.id
     *
     * @return the value of base_role_privilege.id
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_role_privilege.id
     *
     * @param id the value for base_role_privilege.id
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_role_privilege.role_id
     *
     * @return the value of base_role_privilege.role_id
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_role_privilege.role_id
     *
     * @param roleId the value for base_role_privilege.role_id
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_role_privilege.privilege_id
     *
     * @return the value of base_role_privilege.privilege_id
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    public Long getPrivilegeId() {
        return privilegeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_role_privilege.privilege_id
     *
     * @param privilegeId the value for base_role_privilege.privilege_id
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    public void setPrivilegeId(Long privilegeId) {
        this.privilegeId = privilegeId;
    }
}