package com.briup.jz.bean;

import java.io.Serializable;

public class BaseLog implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_log.id
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_log.realname
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    private String realname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_log.method
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    private String method;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_log.content
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_log.log_time
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    private Long logTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table base_log
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_log.id
     *
     * @return the value of base_log.id
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_log.id
     *
     * @param id the value for base_log.id
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_log.realname
     *
     * @return the value of base_log.realname
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_log.realname
     *
     * @param realname the value for base_log.realname
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    public void setRealname(String realname) {
        this.realname = realname == null ? null : realname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_log.method
     *
     * @return the value of base_log.method
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    public String getMethod() {
        return method;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_log.method
     *
     * @param method the value for base_log.method
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    public void setMethod(String method) {
        this.method = method == null ? null : method.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_log.content
     *
     * @return the value of base_log.content
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_log.content
     *
     * @param content the value for base_log.content
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_log.log_time
     *
     * @return the value of base_log.log_time
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    public Long getLogTime() {
        return logTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_log.log_time
     *
     * @param logTime the value for base_log.log_time
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    public void setLogTime(Long logTime) {
        this.logTime = logTime;
    }
}