package com.briup.jz.bean;

import java.io.Serializable;

public class BaseFile implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_file.id
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_file.file_name
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    private String fileName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_file.group_name
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    private String groupName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_file.upload_time
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    private Long uploadTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_file.ext_name
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    private String extName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_file.file_size
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    private Long fileSize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_file.file_type
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    private String fileType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table base_file
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_file.id
     *
     * @return the value of base_file.id
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_file.id
     *
     * @param id the value for base_file.id
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_file.file_name
     *
     * @return the value of base_file.file_name
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_file.file_name
     *
     * @param fileName the value for base_file.file_name
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_file.group_name
     *
     * @return the value of base_file.group_name
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_file.group_name
     *
     * @param groupName the value for base_file.group_name
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName == null ? null : groupName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_file.upload_time
     *
     * @return the value of base_file.upload_time
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    public Long getUploadTime() {
        return uploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_file.upload_time
     *
     * @param uploadTime the value for base_file.upload_time
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    public void setUploadTime(Long uploadTime) {
        this.uploadTime = uploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_file.ext_name
     *
     * @return the value of base_file.ext_name
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    public String getExtName() {
        return extName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_file.ext_name
     *
     * @param extName the value for base_file.ext_name
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    public void setExtName(String extName) {
        this.extName = extName == null ? null : extName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_file.file_size
     *
     * @return the value of base_file.file_size
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    public Long getFileSize() {
        return fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_file.file_size
     *
     * @param fileSize the value for base_file.file_size
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    public void setFileSize(Long fileSize) {
        this.fileSize = fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_file.file_type
     *
     * @return the value of base_file.file_type
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    public String getFileType() {
        return fileType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_file.file_type
     *
     * @param fileType the value for base_file.file_type
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    public void setFileType(String fileType) {
        this.fileType = fileType == null ? null : fileType.trim();
    }
}