package com.briup.jz.bean;

import java.io.Serializable;

public class Carousel implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_carousel.id
     *
     * @mbg.generated Thu Jun 03 18:31:33 CST 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_carousel.name
     *
     * @mbg.generated Thu Jun 03 18:31:33 CST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_carousel.introduce
     *
     * @mbg.generated Thu Jun 03 18:31:33 CST 2021
     */
    private String introduce;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_carousel.url
     *
     * @mbg.generated Thu Jun 03 18:31:33 CST 2021
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_carousel.status
     *
     * @mbg.generated Thu Jun 03 18:31:33 CST 2021
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cms_carousel
     *
     * @mbg.generated Thu Jun 03 18:31:33 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_carousel.id
     *
     * @return the value of cms_carousel.id
     *
     * @mbg.generated Thu Jun 03 18:31:33 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_carousel.id
     *
     * @param id the value for cms_carousel.id
     *
     * @mbg.generated Thu Jun 03 18:31:33 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_carousel.name
     *
     * @return the value of cms_carousel.name
     *
     * @mbg.generated Thu Jun 03 18:31:33 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_carousel.name
     *
     * @param name the value for cms_carousel.name
     *
     * @mbg.generated Thu Jun 03 18:31:33 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_carousel.introduce
     *
     * @return the value of cms_carousel.introduce
     *
     * @mbg.generated Thu Jun 03 18:31:33 CST 2021
     */
    public String getIntroduce() {
        return introduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_carousel.introduce
     *
     * @param introduce the value for cms_carousel.introduce
     *
     * @mbg.generated Thu Jun 03 18:31:33 CST 2021
     */
    public void setIntroduce(String introduce) {
        this.introduce = introduce == null ? null : introduce.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_carousel.url
     *
     * @return the value of cms_carousel.url
     *
     * @mbg.generated Thu Jun 03 18:31:33 CST 2021
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_carousel.url
     *
     * @param url the value for cms_carousel.url
     *
     * @mbg.generated Thu Jun 03 18:31:33 CST 2021
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_carousel.status
     *
     * @return the value of cms_carousel.status
     *
     * @mbg.generated Thu Jun 03 18:31:33 CST 2021
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_carousel.status
     *
     * @param status the value for cms_carousel.status
     *
     * @mbg.generated Thu Jun 03 18:31:33 CST 2021
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}