package com.briup.jz.bean;

import java.io.Serializable;

public class CertificationApply implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jz_certification_apply.id
     *
<<<<<<< HEAD
     * @mbg.generated Thu Jun 03 18:31:33 CST 2021
=======
     * @mbg.generated Thu Jun 03 16:08:43 CST 2021
>>>>>>> 0e922cda61c85a780bd8f647d108582e3274f252
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jz_certification_apply.realname
     *
<<<<<<< HEAD
     * @mbg.generated Thu Jun 03 18:31:33 CST 2021
=======
     * @mbg.generated Thu Jun 03 16:08:43 CST 2021
>>>>>>> 0e922cda61c85a780bd8f647d108582e3274f252
     */
    private String realname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jz_certification_apply.id_card
     *
<<<<<<< HEAD
     * @mbg.generated Thu Jun 03 18:31:33 CST 2021
=======
     * @mbg.generated Thu Jun 03 16:08:43 CST 2021
>>>>>>> 0e922cda61c85a780bd8f647d108582e3274f252
     */
    private String idCard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jz_certification_apply.idcard_photo_positive
     *
<<<<<<< HEAD
     * @mbg.generated Thu Jun 03 18:31:33 CST 2021
=======
     * @mbg.generated Thu Jun 03 16:08:43 CST 2021
>>>>>>> 0e922cda61c85a780bd8f647d108582e3274f252
     */
    private String idcardPhotoPositive;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jz_certification_apply.idcard_photo_negative
     *
<<<<<<< HEAD
     * @mbg.generated Thu Jun 03 18:31:33 CST 2021
=======
     * @mbg.generated Thu Jun 03 16:08:43 CST 2021
>>>>>>> 0e922cda61c85a780bd8f647d108582e3274f252
     */
    private String idcardPhotoNegative;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jz_certification_apply.bank_card
     *
<<<<<<< HEAD
     * @mbg.generated Thu Jun 03 18:31:33 CST 2021
=======
     * @mbg.generated Thu Jun 03 16:08:43 CST 2021
>>>>>>> 0e922cda61c85a780bd8f647d108582e3274f252
     */
    private String bankCard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jz_certification_apply.bank_card_photo
     *
<<<<<<< HEAD
     * @mbg.generated Thu Jun 03 18:31:33 CST 2021
=======
     * @mbg.generated Thu Jun 03 16:08:43 CST 2021
>>>>>>> 0e922cda61c85a780bd8f647d108582e3274f252
     */
    private String bankCardPhoto;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jz_certification_apply.status
     *
<<<<<<< HEAD
     * @mbg.generated Thu Jun 03 18:31:33 CST 2021
=======
     * @mbg.generated Thu Jun 03 16:08:43 CST 2021
>>>>>>> 0e922cda61c85a780bd8f647d108582e3274f252
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jz_certification_apply.apply_time
     *
<<<<<<< HEAD
     * @mbg.generated Thu Jun 03 18:31:33 CST 2021
=======
     * @mbg.generated Thu Jun 03 16:08:43 CST 2021
>>>>>>> 0e922cda61c85a780bd8f647d108582e3274f252
     */
    private Long applyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jz_certification_apply.reason
     *
<<<<<<< HEAD
     * @mbg.generated Thu Jun 03 18:31:33 CST 2021
=======
     * @mbg.generated Thu Jun 03 16:08:43 CST 2021
>>>>>>> 0e922cda61c85a780bd8f647d108582e3274f252
     */
    private String reason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jz_certification_apply.user_id
     *
<<<<<<< HEAD
     * @mbg.generated Thu Jun 03 18:31:33 CST 2021
=======
     * @mbg.generated Thu Jun 03 16:08:43 CST 2021
>>>>>>> 0e922cda61c85a780bd8f647d108582e3274f252
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jz_certification_apply
     *
<<<<<<< HEAD
     * @mbg.generated Thu Jun 03 18:31:33 CST 2021
=======
     * @mbg.generated Thu Jun 03 16:08:43 CST 2021
>>>>>>> 0e922cda61c85a780bd8f647d108582e3274f252
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jz_certification_apply.id
     *
     * @return the value of jz_certification_apply.id
     *
<<<<<<< HEAD
     * @mbg.generated Thu Jun 03 18:31:33 CST 2021
=======
     * @mbg.generated Thu Jun 03 16:08:43 CST 2021
>>>>>>> 0e922cda61c85a780bd8f647d108582e3274f252
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jz_certification_apply.id
     *
     * @param id the value for jz_certification_apply.id
     *
<<<<<<< HEAD
     * @mbg.generated Thu Jun 03 18:31:33 CST 2021
=======
     * @mbg.generated Thu Jun 03 16:08:43 CST 2021
>>>>>>> 0e922cda61c85a780bd8f647d108582e3274f252
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jz_certification_apply.realname
     *
     * @return the value of jz_certification_apply.realname
     *
<<<<<<< HEAD
     * @mbg.generated Thu Jun 03 18:31:33 CST 2021
=======
     * @mbg.generated Thu Jun 03 16:08:43 CST 2021
>>>>>>> 0e922cda61c85a780bd8f647d108582e3274f252
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jz_certification_apply.realname
     *
     * @param realname the value for jz_certification_apply.realname
     *
<<<<<<< HEAD
     * @mbg.generated Thu Jun 03 18:31:33 CST 2021
=======
     * @mbg.generated Thu Jun 03 16:08:43 CST 2021
>>>>>>> 0e922cda61c85a780bd8f647d108582e3274f252
     */
    public void setRealname(String realname) {
        this.realname = realname == null ? null : realname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jz_certification_apply.id_card
     *
     * @return the value of jz_certification_apply.id_card
     *
<<<<<<< HEAD
     * @mbg.generated Thu Jun 03 18:31:33 CST 2021
=======
     * @mbg.generated Thu Jun 03 16:08:43 CST 2021
>>>>>>> 0e922cda61c85a780bd8f647d108582e3274f252
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jz_certification_apply.id_card
     *
     * @param idCard the value for jz_certification_apply.id_card
     *
<<<<<<< HEAD
     * @mbg.generated Thu Jun 03 18:31:33 CST 2021
=======
     * @mbg.generated Thu Jun 03 16:08:43 CST 2021
>>>>>>> 0e922cda61c85a780bd8f647d108582e3274f252
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard == null ? null : idCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jz_certification_apply.idcard_photo_positive
     *
     * @return the value of jz_certification_apply.idcard_photo_positive
     *
<<<<<<< HEAD
     * @mbg.generated Thu Jun 03 18:31:33 CST 2021
=======
     * @mbg.generated Thu Jun 03 16:08:43 CST 2021
>>>>>>> 0e922cda61c85a780bd8f647d108582e3274f252
     */
    public String getIdcardPhotoPositive() {
        return idcardPhotoPositive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jz_certification_apply.idcard_photo_positive
     *
     * @param idcardPhotoPositive the value for jz_certification_apply.idcard_photo_positive
     *
<<<<<<< HEAD
     * @mbg.generated Thu Jun 03 18:31:33 CST 2021
=======
     * @mbg.generated Thu Jun 03 16:08:43 CST 2021
>>>>>>> 0e922cda61c85a780bd8f647d108582e3274f252
     */
    public void setIdcardPhotoPositive(String idcardPhotoPositive) {
        this.idcardPhotoPositive = idcardPhotoPositive == null ? null : idcardPhotoPositive.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jz_certification_apply.idcard_photo_negative
     *
     * @return the value of jz_certification_apply.idcard_photo_negative
     *
<<<<<<< HEAD
     * @mbg.generated Thu Jun 03 18:31:33 CST 2021
=======
     * @mbg.generated Thu Jun 03 16:08:43 CST 2021
>>>>>>> 0e922cda61c85a780bd8f647d108582e3274f252
     */
    public String getIdcardPhotoNegative() {
        return idcardPhotoNegative;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jz_certification_apply.idcard_photo_negative
     *
     * @param idcardPhotoNegative the value for jz_certification_apply.idcard_photo_negative
     *
<<<<<<< HEAD
     * @mbg.generated Thu Jun 03 18:31:33 CST 2021
=======
     * @mbg.generated Thu Jun 03 16:08:43 CST 2021
>>>>>>> 0e922cda61c85a780bd8f647d108582e3274f252
     */
    public void setIdcardPhotoNegative(String idcardPhotoNegative) {
        this.idcardPhotoNegative = idcardPhotoNegative == null ? null : idcardPhotoNegative.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jz_certification_apply.bank_card
     *
     * @return the value of jz_certification_apply.bank_card
     *
<<<<<<< HEAD
     * @mbg.generated Thu Jun 03 18:31:33 CST 2021
=======
     * @mbg.generated Thu Jun 03 16:08:43 CST 2021
>>>>>>> 0e922cda61c85a780bd8f647d108582e3274f252
     */
    public String getBankCard() {
        return bankCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jz_certification_apply.bank_card
     *
     * @param bankCard the value for jz_certification_apply.bank_card
     *
<<<<<<< HEAD
     * @mbg.generated Thu Jun 03 18:31:33 CST 2021
=======
     * @mbg.generated Thu Jun 03 16:08:43 CST 2021
>>>>>>> 0e922cda61c85a780bd8f647d108582e3274f252
     */
    public void setBankCard(String bankCard) {
        this.bankCard = bankCard == null ? null : bankCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jz_certification_apply.bank_card_photo
     *
     * @return the value of jz_certification_apply.bank_card_photo
     *
<<<<<<< HEAD
     * @mbg.generated Thu Jun 03 18:31:33 CST 2021
=======
     * @mbg.generated Thu Jun 03 16:08:43 CST 2021
>>>>>>> 0e922cda61c85a780bd8f647d108582e3274f252
     */
    public String getBankCardPhoto() {
        return bankCardPhoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jz_certification_apply.bank_card_photo
     *
     * @param bankCardPhoto the value for jz_certification_apply.bank_card_photo
     *
<<<<<<< HEAD
     * @mbg.generated Thu Jun 03 18:31:33 CST 2021
=======
     * @mbg.generated Thu Jun 03 16:08:43 CST 2021
>>>>>>> 0e922cda61c85a780bd8f647d108582e3274f252
     */
    public void setBankCardPhoto(String bankCardPhoto) {
        this.bankCardPhoto = bankCardPhoto == null ? null : bankCardPhoto.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jz_certification_apply.status
     *
     * @return the value of jz_certification_apply.status
     *
<<<<<<< HEAD
     * @mbg.generated Thu Jun 03 18:31:33 CST 2021
=======
     * @mbg.generated Thu Jun 03 16:08:43 CST 2021
>>>>>>> 0e922cda61c85a780bd8f647d108582e3274f252
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jz_certification_apply.status
     *
     * @param status the value for jz_certification_apply.status
     *
<<<<<<< HEAD
     * @mbg.generated Thu Jun 03 18:31:33 CST 2021
=======
     * @mbg.generated Thu Jun 03 16:08:43 CST 2021
>>>>>>> 0e922cda61c85a780bd8f647d108582e3274f252
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jz_certification_apply.apply_time
     *
     * @return the value of jz_certification_apply.apply_time
     *
<<<<<<< HEAD
     * @mbg.generated Thu Jun 03 18:31:33 CST 2021
=======
     * @mbg.generated Thu Jun 03 16:08:43 CST 2021
>>>>>>> 0e922cda61c85a780bd8f647d108582e3274f252
     */
    public Long getApplyTime() {
        return applyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jz_certification_apply.apply_time
     *
     * @param applyTime the value for jz_certification_apply.apply_time
     *
<<<<<<< HEAD
     * @mbg.generated Thu Jun 03 18:31:33 CST 2021
=======
     * @mbg.generated Thu Jun 03 16:08:43 CST 2021
>>>>>>> 0e922cda61c85a780bd8f647d108582e3274f252
     */
    public void setApplyTime(Long applyTime) {
        this.applyTime = applyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jz_certification_apply.reason
     *
     * @return the value of jz_certification_apply.reason
     *
<<<<<<< HEAD
     * @mbg.generated Thu Jun 03 18:31:33 CST 2021
=======
     * @mbg.generated Thu Jun 03 16:08:43 CST 2021
>>>>>>> 0e922cda61c85a780bd8f647d108582e3274f252
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jz_certification_apply.reason
     *
     * @param reason the value for jz_certification_apply.reason
     *
<<<<<<< HEAD
     * @mbg.generated Thu Jun 03 18:31:33 CST 2021
=======
     * @mbg.generated Thu Jun 03 16:08:43 CST 2021
>>>>>>> 0e922cda61c85a780bd8f647d108582e3274f252
     */
    public void setReason(String reason) {
        this.reason = reason == null ? null : reason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jz_certification_apply.user_id
     *
     * @return the value of jz_certification_apply.user_id
     *
<<<<<<< HEAD
     * @mbg.generated Thu Jun 03 18:31:33 CST 2021
=======
     * @mbg.generated Thu Jun 03 16:08:43 CST 2021
>>>>>>> 0e922cda61c85a780bd8f647d108582e3274f252
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jz_certification_apply.user_id
     *
     * @param userId the value for jz_certification_apply.user_id
     *
<<<<<<< HEAD
     * @mbg.generated Thu Jun 03 18:31:33 CST 2021
=======
     * @mbg.generated Thu Jun 03 16:08:43 CST 2021
>>>>>>> 0e922cda61c85a780bd8f647d108582e3274f252
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }
}