package com.briup.jz.bean;

import java.io.Serializable;

public class Comment implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_comment.id
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_comment.comment
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    private String comment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_comment.comment_time
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    private Long commentTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_comment.reply
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    private String reply;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_comment.reply_time
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    private Long replyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_comment.status
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_comment.user_id
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_comment.article_id
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    private Long articleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_comment.parent_id
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    private Long parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cms_comment
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_comment.id
     *
     * @return the value of cms_comment.id
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_comment.id
     *
     * @param id the value for cms_comment.id
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_comment.comment
     *
     * @return the value of cms_comment.comment
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_comment.comment
     *
     * @param comment the value for cms_comment.comment
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_comment.comment_time
     *
     * @return the value of cms_comment.comment_time
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    public Long getCommentTime() {
        return commentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_comment.comment_time
     *
     * @param commentTime the value for cms_comment.comment_time
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    public void setCommentTime(Long commentTime) {
        this.commentTime = commentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_comment.reply
     *
     * @return the value of cms_comment.reply
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    public String getReply() {
        return reply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_comment.reply
     *
     * @param reply the value for cms_comment.reply
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    public void setReply(String reply) {
        this.reply = reply == null ? null : reply.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_comment.reply_time
     *
     * @return the value of cms_comment.reply_time
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    public Long getReplyTime() {
        return replyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_comment.reply_time
     *
     * @param replyTime the value for cms_comment.reply_time
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    public void setReplyTime(Long replyTime) {
        this.replyTime = replyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_comment.status
     *
     * @return the value of cms_comment.status
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_comment.status
     *
     * @param status the value for cms_comment.status
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_comment.user_id
     *
     * @return the value of cms_comment.user_id
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_comment.user_id
     *
     * @param userId the value for cms_comment.user_id
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_comment.article_id
     *
     * @return the value of cms_comment.article_id
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    public Long getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_comment.article_id
     *
     * @param articleId the value for cms_comment.article_id
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    public void setArticleId(Long articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_comment.parent_id
     *
     * @return the value of cms_comment.parent_id
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_comment.parent_id
     *
     * @param parentId the value for cms_comment.parent_id
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }
}