package com.briup.jz.bean;

import java.io.Serializable;

public class OrderComment implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jz_order_comment.id
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jz_order_comment.content
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jz_order_comment.comment_time
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    private Long commentTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jz_order_comment.status
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jz_order_comment.order_id
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    private Long orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jz_order_comment.customer_id
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    private Long customerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jz_order_comment
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jz_order_comment.id
     *
     * @return the value of jz_order_comment.id
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jz_order_comment.id
     *
     * @param id the value for jz_order_comment.id
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jz_order_comment.content
     *
     * @return the value of jz_order_comment.content
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jz_order_comment.content
     *
     * @param content the value for jz_order_comment.content
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jz_order_comment.comment_time
     *
     * @return the value of jz_order_comment.comment_time
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    public Long getCommentTime() {
        return commentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jz_order_comment.comment_time
     *
     * @param commentTime the value for jz_order_comment.comment_time
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    public void setCommentTime(Long commentTime) {
        this.commentTime = commentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jz_order_comment.status
     *
     * @return the value of jz_order_comment.status
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jz_order_comment.status
     *
     * @param status the value for jz_order_comment.status
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jz_order_comment.order_id
     *
     * @return the value of jz_order_comment.order_id
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jz_order_comment.order_id
     *
     * @param orderId the value for jz_order_comment.order_id
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jz_order_comment.customer_id
     *
     * @return the value of jz_order_comment.customer_id
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    public Long getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jz_order_comment.customer_id
     *
     * @param customerId the value for jz_order_comment.customer_id
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }
}