package com.briup.jz.bean;

import java.io.Serializable;

public class OrderLine implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jz_order_line.id
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jz_order_line.number
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    private Integer number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jz_order_line.price
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    private Double price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jz_order_line.product_id
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    private Long productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jz_order_line.order_id
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    private Long orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jz_order_line
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jz_order_line.id
     *
     * @return the value of jz_order_line.id
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jz_order_line.id
     *
     * @param id the value for jz_order_line.id
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jz_order_line.number
     *
     * @return the value of jz_order_line.number
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jz_order_line.number
     *
     * @param number the value for jz_order_line.number
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jz_order_line.price
     *
     * @return the value of jz_order_line.price
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jz_order_line.price
     *
     * @param price the value for jz_order_line.price
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jz_order_line.product_id
     *
     * @return the value of jz_order_line.product_id
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jz_order_line.product_id
     *
     * @param productId the value for jz_order_line.product_id
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jz_order_line.order_id
     *
     * @return the value of jz_order_line.order_id
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jz_order_line.order_id
     *
     * @param orderId the value for jz_order_line.order_id
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }
}