package com.briup.jz.bean;

import java.io.Serializable;

public class ProductCategory implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jz_product_category.id
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jz_product_category.name
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jz_product_category.icon
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    private String icon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jz_product_category.num
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    private Integer num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jz_product_category.parent_id
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    private Long parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jz_product_category
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jz_product_category.id
     *
     * @return the value of jz_product_category.id
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jz_product_category.id
     *
     * @param id the value for jz_product_category.id
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jz_product_category.name
     *
     * @return the value of jz_product_category.name
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jz_product_category.name
     *
     * @param name the value for jz_product_category.name
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jz_product_category.icon
     *
     * @return the value of jz_product_category.icon
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jz_product_category.icon
     *
     * @param icon the value for jz_product_category.icon
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    public void setIcon(String icon) {
        this.icon = icon == null ? null : icon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jz_product_category.num
     *
     * @return the value of jz_product_category.num
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jz_product_category.num
     *
     * @param num the value for jz_product_category.num
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jz_product_category.parent_id
     *
     * @return the value of jz_product_category.parent_id
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jz_product_category.parent_id
     *
     * @param parentId the value for jz_product_category.parent_id
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }
}