package com.briup.jz.bean;

import java.io.Serializable;

public class Product implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jz_product.id
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jz_product.name
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jz_product.description
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jz_product.price
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    private Double price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jz_product.status
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jz_product.photo
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    private String photo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jz_product.product_category_id
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    private Long productCategoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jz_product
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jz_product.id
     *
     * @return the value of jz_product.id
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jz_product.id
     *
     * @param id the value for jz_product.id
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jz_product.name
     *
     * @return the value of jz_product.name
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jz_product.name
     *
     * @param name the value for jz_product.name
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jz_product.description
     *
     * @return the value of jz_product.description
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jz_product.description
     *
     * @param description the value for jz_product.description
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jz_product.price
     *
     * @return the value of jz_product.price
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jz_product.price
     *
     * @param price the value for jz_product.price
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jz_product.status
     *
     * @return the value of jz_product.status
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jz_product.status
     *
     * @param status the value for jz_product.status
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jz_product.photo
     *
     * @return the value of jz_product.photo
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    public String getPhoto() {
        return photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jz_product.photo
     *
     * @param photo the value for jz_product.photo
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    public void setPhoto(String photo) {
        this.photo = photo == null ? null : photo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jz_product.product_category_id
     *
     * @return the value of jz_product.product_category_id
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    public Long getProductCategoryId() {
        return productCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jz_product.product_category_id
     *
     * @param productCategoryId the value for jz_product.product_category_id
     *
     * @mbg.generated Wed Jun 02 22:44:48 CST 2021
     */
    public void setProductCategoryId(Long productCategoryId) {
        this.productCategoryId = productCategoryId;
    }
}