package com.evan.jz.dao;

import com.evan.jz.bean.BaseUserRole;
import com.evan.jz.bean.BaseUserRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BaseUserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_user_role
     *
     * @mbg.generated Thu Jun 03 16:08:43 CST 2021
     */
    long countByExample(BaseUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_user_role
     *
     * @mbg.generated Thu Jun 03 16:08:43 CST 2021
     */
    int deleteByExample(BaseUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_user_role
     *
     * @mbg.generated Thu Jun 03 16:08:43 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_user_role
     *
     * @mbg.generated Thu Jun 03 16:08:43 CST 2021
     */
    int insert(BaseUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_user_role
     *
     * @mbg.generated Thu Jun 03 16:08:43 CST 2021
     */
    int insertSelective(BaseUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_user_role
     *
     * @mbg.generated Thu Jun 03 16:08:43 CST 2021
     */
    List<BaseUserRole> selectByExample(BaseUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_user_role
     *
     * @mbg.generated Thu Jun 03 16:08:43 CST 2021
     */
    BaseUserRole selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_user_role
     *
     * @mbg.generated Thu Jun 03 16:08:43 CST 2021
     */
    int updateByExampleSelective(@Param("record") BaseUserRole record, @Param("example") BaseUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_user_role
     *
     * @mbg.generated Thu Jun 03 16:08:43 CST 2021
     */
    int updateByExample(@Param("record") BaseUserRole record, @Param("example") BaseUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_user_role
     *
     * @mbg.generated Thu Jun 03 16:08:43 CST 2021
     */
    int updateByPrimaryKeySelective(BaseUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_user_role
     *
     * @mbg.generated Thu Jun 03 16:08:43 CST 2021
     */
    int updateByPrimaryKey(BaseUserRole record);
}